/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChartBar {
        "echartsData": number[];
        "height": string | number;
        "width": string | number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TestFirst {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TestIonic {
    }
}
export interface ChartBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChartBarElement;
}
declare global {
    interface HTMLChartBarElement extends Components.ChartBar, HTMLStencilElement {
    }
    var HTMLChartBarElement: {
        prototype: HTMLChartBarElement;
        new (): HTMLChartBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestFirstElement extends Components.TestFirst, HTMLStencilElement {
    }
    var HTMLTestFirstElement: {
        prototype: HTMLTestFirstElement;
        new (): HTMLTestFirstElement;
    };
    interface HTMLTestIonicElement extends Components.TestIonic, HTMLStencilElement {
    }
    var HTMLTestIonicElement: {
        prototype: HTMLTestIonicElement;
        new (): HTMLTestIonicElement;
    };
    interface HTMLElementTagNameMap {
        "chart-bar": HTMLChartBarElement;
        "my-component": HTMLMyComponentElement;
        "test-first": HTMLTestFirstElement;
        "test-ionic": HTMLTestIonicElement;
    }
}
declare namespace LocalJSX {
    interface ChartBar {
        "echartsData"?: number[];
        "height"?: string | number;
        "onBarClick"?: (event: ChartBarCustomEvent<any>) => void;
        "width"?: string | number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TestFirst {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TestIonic {
    }
    interface IntrinsicElements {
        "chart-bar": ChartBar;
        "my-component": MyComponent;
        "test-first": TestFirst;
        "test-ionic": TestIonic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chart-bar": LocalJSX.ChartBar & JSXBase.HTMLAttributes<HTMLChartBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-first": LocalJSX.TestFirst & JSXBase.HTMLAttributes<HTMLTestFirstElement>;
            "test-ionic": LocalJSX.TestIonic & JSXBase.HTMLAttributes<HTMLTestIonicElement>;
        }
    }
}
